version: '3'

services:
  web:
    image: pos
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: pos
    volumes:
      - .:/pos
    ports:
      - 8000:8000
